routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Front End Routes
// Front End Routes
Route::get('/website', 'FrontEndController@home')->name('website');
Route::get('/status-update/{id}', 'SalesInchargeController@status_update');


//admin=======
//Admin Routes
// Route::group(['namespace' => 'Admin'], function () {
//     Route::get('admin/home', 'HomeController@index')->name('admin.home');

//     // Admin Auth Routes
//     Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
//     Route::post('admin-login', 'Auth\LoginController@login');
// });
// admin section ...........................................................................


// Admin Panel Routes
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');


});
*/

Route::group(['prefix' => 'admin', 'middleware' => ['verified', 'authadmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');
});


Route::group(['prefix' => 'employee'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('employee.dashboard');

    Route::resource('employeecategory', 'Employee\CategoryController');
    Route::resource('employeepost', 'Employee\PostController');
    Route::resource('employeecustomer', 'Employee\CustomerController');
    Route::resource('employeeattachment', 'Employee\AttachmentController');
    Route::resource('employeetype', 'Employee\TypeController');
    Route::resource('employeeuser', 'Employee\UserController');
    Route::resource('employeesale', 'Employee\SaleController');
    Route::resource('employeedegree', 'Employee\DegreeController');
    Route::resource('employeedivision', 'Employee\DivisionController');
    Route::resource('employeezone', 'Employee\ZoneController');
    Route::resource('employeearea', 'Employee\AreaController');
    Route::resource('employeesales_incharge', 'Employee\SalesInchargeController');
    Route::resource('employeeemployee', 'Employee\EmployeeController');
});
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin','employee']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('type', 'TypeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('employee', 'EmployeeController');


});
*/

app/Employee.php
<?php

namespace App;
use Illuminate\Notifications\Notifiable;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model


{

    use Notifiable;

    protected $fillable = [
        'emp_id','user_id','phone','present_address','permanent_address','image','shop_name',
        'nid_number','nid_image','shop_image','religion','birthdate','marriage_dob','family_member',
        'father_name','mother_name','occupation','business_year','number_of_children','children_dob','division_id',
        'zone_id','area_id'
    ];

    public function division(){
        return $this->belongsTo('App\Division');
    }
    public function zone(){
        return $this->belongsTo('App\Zone');
    }
    public function area(){
        return $this->belongsTo('App\Area');
    }
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function attachments()
    {
        return $this->morphMany('App\Attachment', 'attachable');

    }
    public function sales_incharges()
    {
        return $this->hasMany('App\SaleIncharge');
    }




}

app/Http/Controllers/Employee/AreaController.php
<?php


namespace App\Http\Controllers\Employee;

use Session;
use App\Http\Controllers\Controller;
use App\Division;
use App\Zone;
use App\Area;
use Illuminate\Http\Request;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.area.index', compact('areas'));
    }
}

app/Http/Controllers/Employee/CategoryController.php
<?php

namespace App\Http\Controllers\Employee;

use Session;
use App\Http\Controllers\Controller;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('created_at', 'DESC')->paginate(8);
        return view('employee.category.index', compact('categories'));
    }
}

app/Http/Controllers/Employee/CustomerController.php
<?php

namespace App\Http\Controllers\Employee;


use Session;
use App\Customer;
use App\Category;
use App\Type;
use App\Division;
use App\Zone;
use App\Area;
use App\Attachment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.customer.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = Type::all();
        $categories = Category::all();
        $divisions = Division::with(['zones'])->get();
        $zones = Zone::with(['areas'])->get();
        $areas = Area::all();
        return view('employee.customer.create', compact(['types', 'divisions', 'zones', 'areas', 'categories']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $this->validate($request, [
            'email' => 'required|unique:customers,email',
            'name' => 'required',
            'shop_name' => 'required',
            'phone' => 'required',
            'present_address' => 'required',
            'password' => 'min:6',
            'password_confirm' => 'required_with:password|same:password|min:6',
            'children_dob' => 'before:today',
            'birthdate'  => 'before:-18 years',
            'nid_number' => 'digits_between:11,13',
            'image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',
            'shop_image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',
            'nid_image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',


        ]);


        //dd($request->all());


        $profileImage = $nidImage = $shopImage = null;

        if ($request->hasFile('image')) {
            $image = $request->image;
            $image_new_name = Str::uuid() . '.' . $image->getClientOriginalExtension();
            $image->move('storage/customer/', $image_new_name);
            $profileImage = '/storage/customer/' . $image_new_name;
        }
        if ($request->hasFile('nid_image')) {
            $nid_image = $request->nid_image;
            $image_new_name = Str::uuid() . '.' . $nid_image->getClientOriginalExtension();
            $nid_image->move('storage/customer/', $image_new_name);
            $nidImage = '/storage/customer/' . $image_new_name;
        }
        if ($request->hasFile('shop_image')) {
            $shop_image = $request->shop_image;
            $image_new_name = Str::uuid() . '.' . $shop_image->getClientOriginalExtension();
            $shop_image->move('storage/customer/', $image_new_name);
            $shopImage = '/storage/customer/' . $image_new_name;
        }
        $customer = Customer::create([
            'name' => $request->name,
            'nid_image' => $nidImage,
            'image' => $profileImage,
            'shop_image' => $shopImage,
            'cus_id' => $request->cus_id,
            'nickname' => $request->nickname,
            'phone' => $request->phone,
            'email' => $request->email,
            'present_address' => $request->present_address,
            'permanent_address' => $request->permanent_address,
            'shop_name' => $request->shop_name,
            'nid_number' => $request->nid_number,
            'religion' => $request->religion,
            'birthdate' => $request->birthdate,
            'marriage_dob' => $request->marriage_dob,
            'family_member' => $request->family_member,
            'father_name' => $request->father_name,
            'mother_name' => $request->mother_name,
            'occupation' => $request->occupation,
            'business_year' => $request->business_year,
            'number_of_children' => $request->number_of_children,
            'children_dob' => $request->children_dob,
            'division_id' => $request->division,
            'zone_id' => $request->zone,
            'area_id' => $request->area,
            'type_id' => $request->type,
            'category_id' => $request->category,

        ]);

        Session::flash('success', 'customer  created successfully');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer = Customer::find($id);
        return view('employee.customer.show', compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);
        $types = Type::all();
        $categories = Category::all();
        $divisions = Division::with(['zones'])->get();
        $zones = Zone::with(['areas'])->get();
        $areas = Area::all();
        return view('employee.customer.edit', compact(['customer', 'types', 'divisions', 'zones', 'areas', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $customer = Customer::find($id);
        $this->validate($request, [

            'email' => 'required',
            'name' => 'required',
            'shop_name' => 'required',
            'phone' => 'required',
            'present_address' => 'required',
            'children_dob' => 'before:today',
            'birthdate'  => 'before:-18 years',
            'nid_number' => 'digits_between:11,13',
            'image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',
            'shop_image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',
            'nid_image' => 'mimes:jpg,png,jpeg,gif,svg | max:7000',

        ]);

        $profileImage = $nidImage = $shopImage = null;

        if ($request->hasFile('image')) {
            $image = $request->image;
            $image_new_name = Str::uuid() . '.' . $image->getClientOriginalExtension();
            $image->move('storage/customer/', $image_new_name);
            $profileImage = '/storage/customer/' . $image_new_name;
            $customer->image = $profileImage;
        }
        if ($request->hasFile('nid_image')) {
            $nid_image = $request->nid_image;
            $image_new_name = Str::uuid() . '.' . $nid_image->getClientOriginalExtension();
            $nid_image->move('storage/customer/', $image_new_name);
            $nidImage = '/storage/customer/' . $image_new_name;
            $customer->nid_image = $nidImage;
        }
        if ($request->hasFile('shop_image')) {
            $shop_image = $request->shop_image;
            $image_new_name = Str::uuid() . '.' . $shop_image->getClientOriginalExtension();
            $shop_image->move('storage/customer/', $image_new_name);
            $shopImage = '/storage/customer/' . $image_new_name;
            $customer->shop_image = $shopImage;
        }
        $customer->name = $request->name;
        $customer->cus_id = $request->cus_id;
        $customer->nickname = $request->nickname;
        $customer->phone = $request->phone;
        $customer->email = $request->email;
        $customer->present_address = $request->present_address;
        $customer->permanent_address = $request->permanent_address;
        $customer->religion = $request->religion;
        $customer->type_id = $request->type;
        $customer->shop_name = $request->shop_name;
        $customer->nid_number = $request->nid_number;
        $customer->birthdate = $request->birthdate;
        $customer->marriage_dob = $request->marriage_dob;
        $customer->family_member = $request->family_member;
        $customer->father_name = $request->father_name;
        $customer->mother_name = $request->mother_name;
        $customer->occupation = $request->occupation;
        $customer->business_year = $request->business_year;
        $customer->number_of_children = $request->number_of_children;
        $customer->children_dob = $request->children_dob;
        $customer->division_id = $request->division;
        $customer->zone_id = $request->zone;
        $customer->area_id = $request->area;
        $customer->category_id = $request->category;

        $customer->save();
        Session::flash('success', 'customer  updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        if ($customer) {
            $customer->delete();
            Session::flash('customer deleted successfully');
        }
        return redirect()->back();
    }
}

app/Http/Controllers/Employee/DivisionController.php
<?php

namespace App\Http\Controllers\Employee;

use Session;
use App\Division;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DivisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $divisions = Division::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.division.index', compact('divisions'));
    }
}

app/Http/Controllers/Employee/TypeController.php
<?php

namespace App\Http\Controllers\Employee;

use Session;
use App\Http\Controllers\Controller;
use App\Type;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.type.index', compact('types'));
    }
}

app/Http/Controllers/Employee/ZoneController.php
<?php

namespace App\Http\Controllers\Employee;


use App\Http\Controllers\Controller;
use Session;
use App\Division;
use App\Zone;
use Illuminate\Http\Request;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $zones = Zone::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.zone.index', compact('zones'));
    }
}

resources/views/employee/employee/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Profile HRM Employee</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('website') }}">Home</a></li>
                        <li class="breadcrumb-item active">Profile HRM Employee</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div id="" class="card">
                        <div class="card-header">

                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Profile HRM Employee</h3>
                                <a href="{{ route('employeeemployee.create') }}" class="btn btn-primary">Create HRM Employee</a>
                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th style="width: 10px">Sl No.</th>
                                    <th>Image</th>
                                    <th> Name</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Present Address</th>
                                    <th>Permanent Address</th>
                                    <th>Nid Number</th>
                                    <th>Religion</th>
                                    <th style="width: 130px">Created Date</th>
                                    <th style="width: 40px">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($employees->count())


                                    @foreach ($employees as $employee)
                                        <tr>
                                            <td>{{ $loop->iteration}}</td>

                                            <td>
                                                <div style="max-width: 70px; max-height:70px;overflow:hidden">
                                                    <img src="{{ asset($employee->image) }}" class="img-fluid img-rounded" alt="">
                                                </div>
                                            </td>
                                            <td>{{ optional($employee->user)->name}}</td>
                                            <td>{{ $employee->phone }}</td>
                                            <td>{{ optional($employee->user)->email }}</td>
                                            <td>{{ $employee->present_address }}</td>
                                            <td>{{ $employee->permanent_address }}</td>
                                            <td>{{ $employee->nid_number }}</td>
                                            <td>{{ $employee->religion }}</td>
                                            <td>{{ $employee->created_at }}</td>
                                            <td class="d-flex">
                                                <a href="{{ route('employeeemployee.show', [$employee->id]) }}" class="btn btn-sm btn-success mr-1"> <i class="fas fa-eye"></i> </a>


                                                    <a href="{{ route('employeeemployee.edit', [$employee->id]) }}" class="btn btn-sm btn-primary mr-1"> <i class="fas fa-edit"></i> </a>
                                                    <form action="{{ route('employeeemployee.destroy', [$employee->id]) }}" class="mr-1" method="POST">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="submit" class="btn btn-sm btn-danger"> <i class="fas fa-trash"></i> </button>
                                                    </form>

                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="30">
                                            <h5 class="text-center">No Profile management Info found.</h5>
                                        </td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer d-flex justify-content-center">
                            {{ $employees->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script>

    </script>
@endsection