routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Front End Routes
// Front End Routes
Route::get('/website', 'FrontEndController@home')->name('website');
Route::get('/status-update/{id}', 'SalesInchargeController@status_update');


//admin=======
//Admin Routes
// Route::group(['namespace' => 'Admin'], function () {
//     Route::get('admin/home', 'HomeController@index')->name('admin.home');

//     // Admin Auth Routes
//     Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
//     Route::post('admin-login', 'Auth\LoginController@login');
// });
// admin section ...........................................................................


// Admin Panel Routes
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');


});
*/

Route::group(['prefix' => 'admin', 'middleware' => ['verified', 'authadmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');
});


Route::group(['prefix' => 'employee'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('employee.dashboard');

    Route::resource('employeecategory', 'Employee\CategoryController');
    Route::resource('employeepost', 'Employee\PostController');
    Route::resource('employeecustomer', 'Employee\CustomerController');
    Route::resource('employeeattachment', 'Employee\AttachmentController');
    Route::resource('employeetype', 'Employee\TypeController');
    Route::resource('employeeuser', 'Employee\UserController');
    Route::resource('employeesale', 'Employee\SaleController');
    Route::resource('employeedegree', 'Employee\DegreeController');
    Route::resource('employeedivision', 'Employee\DivisionController');
    Route::resource('employeezone', 'Employee\ZoneController');
    Route::resource('employeearea', 'Employee\AreaController');
    Route::resource('employeesales_incharge', 'Employee\SalesInchargeController');
    Route::resource('employeeemployee', 'Employee\EmployeeController');
});
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin','employee']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('type', 'TypeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('employee', 'EmployeeController');


});
*/

app/Http/Controllers/Employee/TypeController.php
<?php

namespace App\Http\Controllers\Employee;

use Session;
use App\Http\Controllers\Controller;
use App\Type;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.type.index', compact('types'));
    }
}

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;
use Session;
use App\Type;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::orderBy('created_at', 'DESC')->paginate(10);
        return view('admin.type.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation
        $this->validate($request, [
            'name' => 'required|unique:types,name',
        ]);

        $type = Type::create([
            'name' => $request->name,
            'description' => $request->description,
        ]);

        Session::flash('success', 'Customer Type created successfully');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit(Type $type)
    {
        return view('admin.type.edit', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Type $type)
    {
        // validation
        $this->validate($request, [
            'name' => "required|unique:categories,name,$type->id",
        ]);

        $type->name = $request->name;
        $type->description = $request->description;
        $type->save();

        Session::flash('success', 'Customer Type  updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy(Type $type)
    {
        if($type){
            $type->delete();

            Session::flash('success', 'Customer type  deleted successfully');
            return redirect()->route('type.index');
        }
    }

}

resources/views/admin/type/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Customer type</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('website') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('type.index') }}">Customer type list</a></li>
                        <li class="breadcrumb-item active">Create Customer type</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Create Customer type</h3>
                                <a href="{{ route('type.index') }}" class="btn btn-primary">Go Back to Customer type List</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                                    <form action="{{ route('type.store') }}" method="POST">
                                        @csrf
                                        <div class="card-body">
                                            @include('includes.errors')
                                            <div class="form-group">
                                                <label for="name">Customer type </label>
                                                <input type="name" name="name" class="form-control" id="name" placeholder="Enter name">
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Description</label>
                                                <textarea name="description" id="description" rows="4" class="form-control"
                                                          placeholder="Enter description"></textarea>
                                            </div>
                                        </div>

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/type/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Edit Customer Type</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('website') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('type.index') }}">Customer Type list</a></li>
                        <li class="breadcrumb-item active">Edit Customer Type</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Edit Customer Type - {{ $type->name }}</h3>
                                <a href="{{ route('type.index') }}" class="btn btn-primary">Go Back to Customer Type List</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                                    <form action="{{ route('type.update', [$type->id]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <div class="card-body">
                                            @include('includes.errors')
                                            <div class="form-group">
                                                <label for="name">Customer Type </label>
                                                <input type="name" name="name" class="form-control" value="{{ $type->name }}" placeholder="Enter name">
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Description</label>
                                                <textarea name="description" id="description" rows="4" class="form-control"
                                                          placeholder="Enter description"> {{ $type->description }} </textarea>
                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-lg btn-primary">Update Customer Type</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/type/index.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Type List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('website')}}">Home</a></li>
                        <li class="breadcrumb-item active">Customer Type</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header ">
                            <h3 class="card-title">Customer Type List</h3>
                            <div class="d-flex justify-content-end">
                                <a href="{{route('type.create')}}" class="btn btn-primary">Create Customer Type</a>
                        </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th style="width: 250px">Sl No.</th>
                                    <th>Customer Type Name</th>


                                    <th style="width: 100px">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($types->count()>0)


                                @foreach($types as $type)

                                <tr>
                                    <td>{{$loop->iteration}}</td>

                                    <td>{{$type->name}}</td>

                                    <td class="d-flex">
                                        <a href="{{ route('type.edit', [$type->id]) }}" class="btn btn-sm btn-primary mr-1"> <i class="fas fa-edit"></i> </a>
                                        <form action="{{ route('type.destroy', [$type->id]) }}" class="mr-1" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-danger"> <i class="fas fa-trash"></i> </button>
                                        </form>
                                        <a href="{{ route('type.show', [$type->id]) }}" class="btn btn-sm btn-success mr-1"> <i class="fas fa-eye"></i> </a>
                                    </td>
                                     </tr>
                                    @endforeach
                                @else
                                <tr>
                                    <td colspan="5">
                                        <h5 class="text-center">No Customer Type Found</h5>
                                    </td>
                                </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->

                    </div>
                   

                </div>
            </div>
        </div>
    </div>
</div>

@endsection