routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Front End Routes
// Front End Routes
Route::get('/website', 'FrontEndController@home')->name('website');
Route::get('/status-update/{id}', 'SalesInchargeController@status_update');


//admin=======
//Admin Routes
// Route::group(['namespace' => 'Admin'], function () {
//     Route::get('admin/home', 'HomeController@index')->name('admin.home');

//     // Admin Auth Routes
//     Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
//     Route::post('admin-login', 'Auth\LoginController@login');
// });
// admin section ...........................................................................


// Admin Panel Routes
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');


});
*/

Route::group(['prefix' => 'admin', 'middleware' => ['verified', 'authadmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');

    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('attachment', 'AttachmentController');
    Route::resource('type', 'TypeController');
    Route::resource('user', 'UserController');
    Route::resource('sale', 'SaleController');
    Route::resource('degree', 'DegreeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('sales_incharge', 'SalesInchargeController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('role', 'RoleController');
});


Route::group(['prefix' => 'employee'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('employee.dashboard');

    Route::resource('employeecategory', 'Employee\CategoryController');
    Route::resource('employeepost', 'Employee\PostController');
    Route::resource('employeecustomer', 'Employee\CustomerController');
    Route::resource('employeeattachment', 'Employee\AttachmentController');
    Route::resource('employeetype', 'Employee\TypeController');
    Route::resource('employeeuser', 'Employee\UserController');
    Route::resource('employeesale', 'Employee\SaleController');
    Route::resource('employeedegree', 'Employee\DegreeController');
    Route::resource('employeedivision', 'Employee\DivisionController');
    Route::resource('employeezone', 'Employee\ZoneController');
    Route::resource('employeearea', 'Employee\AreaController');
    Route::resource('employeesales_incharge', 'Employee\SalesInchargeController');
    Route::resource('employeeemployee', 'Employee\EmployeeController');
});
/*
Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin','employee']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('post', 'PostController');
    Route::resource('customer', 'CustomerController');
    Route::resource('type', 'TypeController');
    Route::resource('division', 'DivisionController');
    Route::resource('zone', 'ZoneController');
    Route::resource('area', 'AreaController');
    Route::resource('employee', 'EmployeeController');


});
*/

app/Zone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Zone extends Model
{
    protected $guarded = ['created_at', 'deleted_at', 'updated_at'];

    public function division(){
        return $this->belongsTo('App\Division');
    }
    public function areas()
    {
        return $this->hasMany('App\Area');
    }

}

app/Http/Controllers/Employee/ZoneController.php
<?php

namespace App\Http\Controllers\Employee;


use App\Http\Controllers\Controller;
use Session;
use App\Division;
use App\Zone;
use Illuminate\Http\Request;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $zones = Zone::orderBy('created_at', 'DESC')->paginate(10);
        return view('employee.zone.index', compact('zones'));
    }
}

app/Http/Controllers/ZoneController.php
<?php

namespace App\Http\Controllers;
use Session;
use App\Division;
use App\Zone;
use Illuminate\Http\Request;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $zones = Zone::orderBy('created_at', 'DESC')->paginate(10);
        return view('admin.zone.index', compact('zones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisions= Division::all();
        //dd($divisions);
        return view('admin.zone.create', compact(['divisions']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation
        $this->validate($request, [
            'name' => 'required'
        ]);

        $zone= Zone::create([
            'name' => $request->name,
            'division_id' => $request->division,
        ]);

        Session::flash('success', 'Division created successfully');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function show(Zone $zone)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function edit(Zone $zone)
    {
        $divisions= Division::all();
        return view('admin.zone.edit', compact('zone','divisions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Zone $zone)
    {
        // validation
        $this->validate($request, [
            'name' => "required"
        ]);
        $zone->name = $request->name;
        $zone-> division_id = $request->division;
        $zone->save();

        Session::flash('success', 'Zone updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Zone $zone)
    {
        if($zone){
            $zone->delete();

            Session::flash('success', 'Zone deleted successfully');
            return redirect()->route('zone.index');
        }
    }
}

resources/views/admin/zone/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Zone</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('website') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('zone.index') }}">Zone list</a></li>
                        <li class="breadcrumb-item active">Create Zone</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Create Zone</h3>
                                <a href="{{ route('zone.index') }}" class="btn btn-primary">Go Back to Zone List</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                                    <form action="{{ route('zone.store') }}" method="POST">
                                        @csrf
                                        <div class="card-body">
                                            @include('includes.errors')
                                            <div class="form-group ">
                                                <label for="division">Division Name</label>
                                                <select name="division" id="division" class="form-control">
                                                    <option value="" style="display: none" selected>Select Division Name</option>
                                                    @foreach($divisions as $d)
                                                        <option value="{{ $d->id }}"> {{ $d->name }} </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="name"> Zone Name </label>
                                                <input type="name" name="name" class="form-control" id="name" placeholder="Enter name">
                                            </div>


                                        </div>

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/zone/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Edit Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('website') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('zone.index') }}">Zone list</a></li>
                        <li class="breadcrumb-item active">Edit  zone</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Edit Zone- {{ $zone->name }}</h3>
                                <a href="{{ route('zone.index') }}" class="btn btn-primary">Go Back to Zone List</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                                    <form action="{{ route('zone.update', [$zone->id]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <div class="card-body">
                                            @include('includes.errors')
                                            <div class="form-group ">
                                                <label for="division">Division Name</label>
                                                <select name="division" id="division" class="form-control">
                                                    <option value="" style="display: none" selected>Select Customer type</option>
                                                    @foreach($divisions as $d)
                                                        <option value="{{ $d->id }}"> @if($zone->division_id == $d->id) selected @endif> {{ $d->name }}</option>

                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="name">Zone Name</label>
                                                <input type="name" name="name" class="form-control" value="{{ $zone->name }}" placeholder="Enter name">
                                            </div>

                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-lg btn-primary">Update  zone</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/zone/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Zone List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('website')}}">Home</a></li>
                        <li class="breadcrumb-item active">Zone</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header ">
                            <h3 class="card-title">Zone List</h3>
                            <div class="d-flex justify-content-end">
                                <a href="{{route('zone.create')}}" class="btn btn-primary">Create Zone</a>
                        </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th style="width: 250px">Sl No.</th>
                                    <th> Division Name</th>
                                    <th> Zone name</th>


                                    <th style="width: 100px">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($zones->count()>0)
                                <?php $number = 1; ?>

                                @foreach($zones as $zone)

                                <tr>
                                    <td>{{$number}}</td>
                                    <?php $number++; ?>
                                    <td>{{optional($zone->division)->name }}</td>
                                    <td>{{$zone->name}}</td>
                                    <td class="d-flex">
                                        <a href="{{ route('zone.edit', [$zone->id]) }}" class="btn btn-sm btn-primary mr-1"> <i class="fas fa-edit"></i> </a>
                                        <form action="{{ route('zone.destroy', [$zone->id]) }}" class="mr-1" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-danger"> <i class="fas fa-trash"></i> </button>
                                        </form>
                                        <a href="{{ route('zone.show', [$zone->id]) }}" class="btn btn-sm btn-success mr-1"> <i class="fas fa-eye"></i> </a>
                                    </td>
                                     </tr>
                                    @endforeach
                                @else
                                <tr>
                                    <td colspan="5">
                                        <h5 class="text-center">No Zone Found</h5>
                                    </td>
                                </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer d-flex justify-content-center">
                            {{$zones->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection